language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - pip install pep8==1.7.0
  - pip install pyflakes==1.3.0
  - pip install pytest==3.0.3
  - pip install pytest-flakes==1.0.1
  - pip install pytest-pep8==1.0.6
  - pip install requests_mock==1.1.0
  - pip install pytest-cov==2.4.0
  - pip install coveralls==1.1
  - python setup.py develop
# command to run tests
script:
  - pwd
  - ls
  - set
  - py.test --flakes --cov=pyloginsight --cov-config=tox.ini --cov-fail-under=60 --cov-report term-missing
after_success: coveralls