language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - pip install pep8==1.7.0
  - pip install pyflakes==1.3.0
  - pip install pytest==3.0.3
  - pip install pytest-flakes==1.0.1
  - pip install pytest-pep8==1.0.6
  - pip install requests_mock==1.1.0
  - python setup.py install
# command to run tests
script: py.test --flakes  #--pep8
